local function setup(c, opts)
    local highlights = {
        ["@error"] = { fg = c.error, bg = "NONE" },
        ["@punctuation.bracket"] = { fg = c.front, bg = "NONE" },
        ["@punctuation.special"] = { fg = c.front, bg = "NONE" },
        ["@punctuation.delimiter"] = { fg = c.front, bg = "NONE" },
        ["@comment"] = {
            fg = c.gray,
            bg = "NONE",
            italic = opts.italic_comments,
        },
        ["@comment.note"] = { fg = c.greenBlue, bg = "NONE", bold = true },
        ["@comment.warning"] = {
            fg = c.yellowOrange,
            bg = "NONE",
            bold = true,
        },
        ["@comment.error"] = { fg = c.error, bg = "NONE", bold = true },
        ["@constant"] = { fg = c.orange, bg = "NONE" },
        ["@constant.builtin"] = { fg = c.blue, bg = "NONE" },
        ["@constant.macro"] = { fg = c.greenBlue, bg = "NONE" },
        ["@string.regexp"] = { fg = c.orange, bg = "NONE" },
        ["@string"] = { fg = c.green, bg = "NONE" },
        ["@character"] = { fg = c.green, bg = "NONE" },
        ["@number"] = { fg = c.lightGreen, bg = "NONE" },
        ["@number.float"] = { fg = c.lightGreen, bg = "NONE" },
        ["@boolean"] = { fg = c.orange, bg = "NONE" },
        ["@annotation"] = { fg = c.red, bg = "NONE" },
        ["@attribute"] = { fg = c.red, bg = "NONE" },
        ["@attribute.builtin"] = { fg = c.greenBlue, bg = "NONE" },
        ["@module"] = { fg = c.greenBlue, bg = "NONE" },
        ["@function"] = { fg = c.red, bg = "NONE" },
        ["@function.builtin"] = { fg = c.red, bg = "NONE" },
        ["@function.macro"] = { fg = c.red, bg = "NONE" },
        ["@function.method"] = { fg = c.red, bg = "NONE" },
        ["@variable"] = { fg = c.lightBlue, bg = "NONE" },
        ["@variable.builtin"] = { fg = c.accentBlue, bg = "NONE" },
        ["@variable.parameter"] = { fg = c.front, bg = "NONE" },
        ["@variable.parameter.reference"] = { fg = c.front, bg = "NONE" },
        ["@variable.member"] = { fg = c.front, bg = "NONE" },
        ["@property"] = { fg = c.lightBlue, bg = "NONE" },
        ["@constructor"] = { fg = c.blue, bg = "NONE" },
        ["@label"] = { fg = c.lightBlue, bg = "NONE" },
        ["@keyword"] = { fg = c.pink, bg = "NONE" },
        ["@keyword.conditional"] = { fg = c.pink, bg = "NONE" },
        ["@keyword.repeat"] = { fg = c.pink, bg = "NONE" },
        ["@keyword.return"] = { fg = c.pink, bg = "NONE" },
        ["@keyword.exception"] = { fg = c.pink, bg = "NONE" },
        ["@keyword.import"] = { fg = c.pink, bg = "NONE" },
        ["@operator"] = { fg = c.pink, bg = "NONE" },
        ["@type"] = { fg = c.accentBlue, bg = "NONE" },
        ["@type.qualifier"] = { fg = c.accentBlue, bg = "NONE" },
        ["@structure"] = { fg = c.greenBlue, bg = "NONE" },
        ["@tag"] = { fg = c.lightGreen, bg = "NONE" },
        ["@tag.delimiter"] = { fg = c.front, bg = "NONE" },
        ["@tag.attribute"] = { fg = c.orange, bg = "NONE" },
        ["@text"] = { fg = c.front, bg = "NONE" },
        ["@markup.strong"] = { fg = c.blue, bold = true },
        ["@markup.italic"] = { fg = c.front, bg = "NONE", italic = true },
        ["@markup.underline"] = {
            fg = c.yellowOrange,
            bg = "NONE",
            underline = true,
        },
        ["@markup.strikethrough"] = {
            fg = c.front,
            bg = "NONE",
            strikethrough = true,
        },
        ["@markup.heading"] = { fg = c.blue, bold = true },
        ["@markup.raw"] = { fg = c.front, bg = "NONE" },
        ["@markup.raw.markdown"] = { fg = c.orange, bg = "NONE" },
        ["@markup.raw.markdown_inline"] = { fg = c.orange, bg = "NONE" },
        ["@markup.link.label"] = {
            fg = c.lightBlue,
            bg = "NONE",
            underline = opts.underline_links,
        },
        ["@markup.link.url"] = {
            fg = c.front,
            bg = "NONE",
            underline = opts.underline_links,
        },
        ["@markup.list.checked"] = { link = "Todo" },
        ["@markup.list.unchecked"] = { link = "Todo" },
        ["@textReference"] = { fg = c.orange },
        ["@stringEscape"] = { fg = c.orange, bold = true },
        ["@diff.plus"] = { link = "DiffAdd" },
        ["@diff.minus"] = { link = "DiffDelete" },
        ["@diff.delta"] = { link = "DiffChange" },
    }

    return highlights
end

return { setup = setup }
